# Project
version=1.20.1-1.0.0
group=net.cama.walljumpvs

# Common
minecraft_version=1.20.1
configlibtxf_version=4.2.8

# Forge
forge_version=1.20.1-47.4.13
forge_version_range=[46,)
forge_loader_version_range=[46,)
forge_minecraft_version_range=[1.20,1.20.2)
forge_side=BOTH

# Fabric
fabric_api_version=0.91.0+1.20.1
fabric_loader_version=0.16.7
fabric_loader_version_range=>=0.15.0
fabric_minecraft_version_range=>=1.20 <1.20.2
fabric_side=*
keybindfixtxf_version=1.1.1

# Mod options
mod_name=Wall-JumpVS
mod_author=cama
mod_id=walljumpvs
mod_license=GPL3
mod_description=Wall jump, double jump, fence jump & more, with VS support!
mod_url=
mod_issues=

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false